-- Shesheny Motors Supabase Schema

-- ==========================================
-- 1. Create Tables
-- ==========================================

-- Vehicles Table
CREATE TABLE public.vehicles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    brand text NOT NULL,
    model text NOT NULL,
    year integer NOT NULL,
    price_egp numeric NOT NULL,
    price_usd numeric NOT NULL,
    color text NOT NULL,
    condition text NOT NULL,
    hp text NOT NULL,
    acceleration numeric NOT NULL,
    miles integer NOT NULL,
    video_url text,
    thumbnail text NOT NULL,
    gallery text[] DEFAULT '{}'::text[],
    is_spotlight boolean DEFAULT false
);

-- Settings Table (Global Config)
CREATE TABLE public.settings (
    id integer PRIMARY KEY,
    whatsapp_number text,
    call_number text,
    map_embed text,
    event_theme text DEFAULT 'none',
    instagram text,
    facebook text,
    tiktok text,
    exchange_rate numeric DEFAULT 50.0,
    hero_image text
);

-- Inquiries Table
CREATE TABLE public.inquiries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "firstName" text NOT NULL,
    "lastName" text NOT NULL,
    email text NOT NULL,
    phone text,
    "inquiryType" text NOT NULL,
    message text NOT NULL
);

-- ==========================================
-- 2. Insert Default Data
-- ==========================================

-- Insert the default settings row
INSERT INTO public.settings (id, whatsapp_number, call_number, map_embed, event_theme, instagram, facebook, tiktok)
VALUES (
    1, 
    '+201067776777', 
    '+201067776777', 
    '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d110502.61185040645!2d31.1765851!3d30.0596113!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14583fa60b21beeb%3A0x79dfb296e8423bba!2sCairo%2C%20Cairo%20Governorate!5e0!3m2!1sen!2seg!4v1700000000000!5m2!1sen!2seg" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
    'none',
    'https://instagram.com/shesheny',
    'https://facebook.com/shesheny',
    'https://tiktok.com/@shesheny'
) ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- 3. Row Level Security (RLS) Policies
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Vehicles: Anyone can read, only authenticated users (admin) can insert/update/delete
CREATE POLICY "Allow public read access on vehicles" ON public.vehicles FOR SELECT USING (true);
CREATE POLICY "Allow auth insert on vehicles" ON public.vehicles FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow auth update on vehicles" ON public.vehicles FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow auth delete on vehicles" ON public.vehicles FOR DELETE TO authenticated USING (true);

-- Settings: Anyone can read, only authenticated users can update
CREATE POLICY "Allow public read access on settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow auth update on settings" ON public.settings FOR UPDATE TO authenticated USING (true);
-- Prevent deletion/insertion of settings by anyone to protect the single row
CREATE POLICY "Prevent delete on settings" ON public.settings FOR DELETE USING (false);
CREATE POLICY "Prevent insert on settings" ON public.settings FOR INSERT WITH CHECK (false);

-- Inquiries: Anyone can insert (submit form), only authenticated can read/update/delete
CREATE POLICY "Allow public insert on inquiries" ON public.inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow auth read on inquiries" ON public.inquiries FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow auth update on inquiries" ON public.inquiries FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow auth delete on inquiries" ON public.inquiries FOR DELETE TO authenticated USING (true);

-- ==========================================
-- 4. Storage Buckets Setup
-- ==========================================
-- Note: It is often easier to create buckets via the Supabase UI. 
-- However, running the below will create a public bucket named "vehicles" if it doesn't exist.

INSERT INTO storage.buckets (id, name, public)
VALUES ('vehicles', 'vehicles', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Policies
-- Allow public access to read images from the vehicles bucket
CREATE POLICY "Give public access to vehicles bucket" ON storage.objects FOR SELECT USING (bucket_id = 'vehicles');

-- Allow authenticated users to upload, update, and delete images in the vehicles bucket
CREATE POLICY "Allow auth upload to vehicles bucket" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'vehicles');
CREATE POLICY "Allow auth update to vehicles bucket" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'vehicles');
CREATE POLICY "Allow auth delete from vehicles bucket" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'vehicles');
