-- Drop existing Shesheny tables to avoid conflicts with new Legend schema
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.inquiries CASCADE;
DROP TABLE IF EXISTS public.vehicles CASCADE;

-- Drop new Legend tables if they exist for a clean slate
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.brands CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;

-- Create Brands table
CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

-- Create policies (Idempotent)
DROP POLICY IF EXISTS "Allow public read-only access" ON public.brands;
CREATE POLICY "Allow public read-only access" ON public.brands
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin full access" ON public.brands;
CREATE POLICY "Allow admin full access" ON public.brands
    FOR ALL USING (auth.role() = 'authenticated');
-- Create Categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ar TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS "Allow public read-only access" ON public.categories;
CREATE POLICY "Allow public read-only access" ON public.categories
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin full access" ON public.categories;
CREATE POLICY "Allow admin full access" ON public.categories
    FOR ALL USING (auth.role() = 'authenticated');

-- Seed initial categories if empty
INSERT INTO public.categories (name, name_ar)
SELECT name, name FROM (
    VALUES ('Sedan'), ('SUV'), ('Coupe'), ('Sports'), ('Luxury')
) AS t(name)
WHERE NOT EXISTS (SELECT 1 FROM public.categories);
-- Ensure Brands table exists before Products (though proper order is running brands.sql first)
-- Create Products table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ar TEXT,
    price_egp NUMERIC,
    category TEXT,
    brand_id BIGINT REFERENCES public.brands(id),
    origin TEXT, -- 'Imported' or 'Egyptian Agency'
    is_imported BOOLEAN DEFAULT true,
    is_spotlight BOOLEAN DEFAULT false,
    is_upon_request BOOLEAN DEFAULT false,
    is_sold_out BOOLEAN DEFAULT false,
    description TEXT,
    description_ar TEXT,
    mileage TEXT,
    fuel_type TEXT,
    transmission TEXT,
    version TEXT,
    image_url TEXT,
    gallery TEXT[], -- Array of image URLs
    diagnostics_url TEXT,
    color TEXT,
    color_ar TEXT,
    order_explore INTEGER DEFAULT 0,
    order_spotlight INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create policies (Idempotent)
DROP POLICY IF EXISTS "Allow public read-only access" ON public.products;
CREATE POLICY "Allow public read-only access" ON public.products
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin full access" ON public.products;
CREATE POLICY "Allow admin full access" ON public.products
    FOR ALL USING (auth.role() = 'authenticated');
-- Migration: Add color_variants JSONB column to products
-- Run this in the Supabase SQL editor

-- Add the new column (stored as JSONB array of {name, name_ar, hex, gallery} objects)
ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS color_variants JSONB DEFAULT '[]'::jsonb;

-- Optional: migrate any existing color text data into the new format
-- (Only run this if you want to preserve old single-color data)
-- UPDATE public.products
--     SET color_variants = jsonb_build_array(
--         jsonb_build_object(
--             'name', COALESCE(color, 'Default'),
--             'name_ar', COALESCE(color_ar, ''),
--             'hex', '#888888',
--             'gallery', COALESCE(gallery, '[]'::jsonb)
--         )
--     )
-- WHERE color IS NOT NULL AND color != '' AND (color_variants IS NULL OR color_variants = '[]'::jsonb);
-- Create Messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    subject TEXT,
    message TEXT,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public insert access" ON public.messages
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admin full access" ON public.messages
    FOR ALL USING (auth.role() = 'authenticated');
-- Create Settings table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read-only access" ON public.settings
    FOR SELECT USING (true);

CREATE POLICY "Allow admin full access" ON public.settings
    FOR ALL USING (auth.role() = 'authenticated');

-- Insert default settings
INSERT INTO public.settings (key, value) VALUES
('exchange_rate', '50.0'),
('instagram_link', '#'),
('facebook_link', '#'),
('tiktok_link', '#'),
('whatsapp_number', '#'),
('phone_number', '#'),
('map_iframe_source', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3455.776625845564!2d31.4287661!3d29.986!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14583d7a8d88697b%3A0x6b696f8a846f6f6b!2sNew%20Cairo%2C%20Egypt!5e0!3m2!1sen!2seg!4v1620000000000!5m2!1sen!2seg'),
('hero_image', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQ0mG099vYpqNDbpLyTIVB-qWTjo0OdFfTRPUsHn2tpTWRGAEFevvT9lHQ-poel8v9BCCyXsGvKJw8iD5V_OFoJAgcfx3SM4mifTY-Bq-9SGUoEYyGq11kzsFQlIbvMJ0wRT1Feh67PrJf40PFTIhPDWLihdQV0um1l1KSWyusNuLgQckK1t3QrdGREKTDAGyLO3Pi7x7A3mhpMez9T6S8m3qjM9m5fh0l8mAW07RFKy_h2Q7ZhNpe4Skxi3mbUq49A8CDGT8Cs1or'),
('website_links', '[]')
ON CONFLICT (key) DO NOTHING;
-- Create the bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('vehicle-images', 'vehicle-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Note: RLS on storage.objects is enabled by default in Supabase.
-- If you encounter permission errors, ensure the bucket exists and policies are applied.

-- Allow public access to images (SELECT)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'objects'
        AND schemaname = 'storage'
        AND policyname = 'Public Access'
    ) THEN
        CREATE POLICY "Public Access"
        ON storage.objects FOR SELECT
        USING ( bucket_id = 'vehicle-images' );
    END IF;
END $$;

-- Allow authenticated users to upload images (INSERT)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'objects'
        AND schemaname = 'storage'
        AND policyname = 'Authenticated Insert'
    ) THEN
        CREATE POLICY "Authenticated Insert"
        ON storage.objects FOR INSERT
        WITH CHECK (
            bucket_id = 'vehicle-images' AND
            auth.role() = 'authenticated'
        );
    END IF;
END $$;

-- Allow authenticated users to update their images (UPDATE)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'objects'
        AND schemaname = 'storage'
        AND policyname = 'Authenticated Update'
    ) THEN
        CREATE POLICY "Authenticated Update"
        ON storage.objects FOR UPDATE
        USING (
            bucket_id = 'vehicle-images' AND
            auth.role() = 'authenticated'
        );
    END IF;
END $$;

-- Allow authenticated users to delete their images (DELETE)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'objects'
        AND schemaname = 'storage'
        AND policyname = 'Authenticated Delete'
    ) THEN
        CREATE POLICY "Authenticated Delete"
        ON storage.objects FOR DELETE
        USING (
            bucket_id = 'vehicle-images' AND
            auth.role() = 'authenticated'
        );
    END IF;
END $$;
-- NOTE: This seed file assumes brands with IDs 1, 2, 3 exist.
-- It is recommended to run brands.sql and products.sql before this.

-- Sample Brands
INSERT INTO public.brands (name, logo_url) VALUES
('Mercedes-Benz', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Benz_logo.svg/2048px-Mercedes-Benz_logo.svg.png'),
('BMW', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/2048px-BMW.svg.png'),
('Porsche', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Porsche-logo.svg/1200px-Porsche-logo.svg.png'),
('Audi', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/2560px-Audi-Logo_2016.svg.png')
ON CONFLICT DO NOTHING;

-- Sample Products
INSERT INTO public.products (
    name, name_ar, price_egp, category, brand_id, origin, is_spotlight, is_upon_request, is_sold_out,
    description, description_ar, mileage, fuel_type, transmission, version,
    image_url, gallery, order_explore, order_spotlight
) VALUES
(
    'Mercedes-Benz G63 AMG', 'مرسيدس جي 63 AMG', 12500000, 'SUV', 1, 'Imported', true, false, false,
    'The legendary G-Wagon, unmatched performance and luxury.', 'جي واجون الأسطورية، أداء وفخامة لا مثيل لهما.',
    '0 km', 'Petrol', 'Automatic', 'AMG',
    'https://images.unsplash.com/photo-1520031441872-265e4ff70366?q=80&w=2070&auto=format&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1520031441872-265e4ff70366?q=80&w=2070&auto=format&fit=crop'],
    0, 0
),
(
    'BMW M4 Competition', 'بي إم دبليو M4 كومبيتشن', 6800000, 'Coupe', 2, 'Egyptian Agency', true, false, false,
    'Pure driving pleasure with M power.', 'متعة القيادة الخالصة مع قوة M.',
    '1,200 km', 'Petrol', 'Automatic', 'Competition',
    'https://images.unsplash.com/photo-1617814076668-8dfc6fe159c7?q=80&w=2070&auto=format&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1617814076668-8dfc6fe159c7?q=80&w=2070&auto=format&fit=crop'],
    1, 1
),
(
    'Porsche 911 GT3 RS', 'بورش 911 GT3 RS', 15000000, 'Sports', 3, 'Imported', true, true, false,
    'The ultimate track machine for the road.', 'آلة الحلبة المثالية للطريق.',
    '0 km', 'Petrol', 'PDK', 'GT3 RS',
    'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?q=80&w=1974&auto=format&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1614200187524-dc4b892acf16?q=80&w=1974&auto=format&fit=crop'],
    2, 2
)
ON CONFLICT DO NOTHING;
